[package]
name = "naga"
version = "0.2.0"
authors = ["Dzmitry Malyshau <kvarkus@gmail.com>"]
edition = "2018"
description = "Shader translation infrastructure"
homepage = "https://github.com/gfx-rs/naga"
repository = "https://github.com/gfx-rs/naga"
keywords = ["shader", "SPIR-V"]
license = "MIT OR Apache-2.0"

[dependencies]
bitflags = "1"
fxhash = "0.2"
log = "0.4"
num-traits = "0.2"
spirv = { package = "spirv_headers", version = "1.4.2", optional = true }
glsl = { version = "4.1", optional = true }
pomelo = { version = "0.1.4", optional = true }
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"], optional = true }

[features]
default = []
glsl_preprocessor = ["glsl"]
glsl-new = ["pomelo"]
glsl-validate = []
glsl-out = []
serialize = ["serde"]
deserialize = ["serde"]

[dev-dependencies]
env_logger = "0.7"
ron = "0.6"
serde = { version = "1.0", features = ["derive"] }
